# Netlify configuration for Villa Luisetta
[build]
  publish = "dist/VillaLuisetta"
  command = "npm run build"

# Force HTTPS redirects
[[redirects]]
  from = "http://villaluisetta.it/*"
  to = "https://www.villaluisetta.it/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.villaluisetta.it/*"
  to = "https://www.villaluisetta.it/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://villaluisetta.it/*"
  to = "https://www.villaluisetta.it/:splat"
  status = 301
  force = true

# SPA fallback for Angular routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers configuration
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# SSL/TLS Configuration
[context.production.environment]
  HTTPS = "true"

# Custom domain configuration
[[edge_handlers]]
  pattern = "/*"
  function = "force-https"